name: Tag and Release

on:
  workflow_dispatch:
   inputs:
    tag-number:
      type: string
      description: "Provide the tag number"
      required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Tag
        run: |
          git config --local user.name ${{ github.actor }}
          git tag -a "v${{ github.event.inputs.tag-number }}" -m "Release v${{ github.event.inputs.tag-number }}"
          git push origin "v${{ github.event.inputs.tag-number }}"
      - name: Create Release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ github.event.inputs.tag-number }}'
          release_name: 'Release v${{ github.event.inputs.tag-number }}'
          body: 'This is the first release'
